### ISSUE TITLE
Implement stock metrics

### ISSUE THREAD

**Issue by ArabianCoconut** [ArabianCoconut/Moneycontrol_api#24]
- To implement various metrics stock such as price, P/E ratio, etc.

**Comment by stunzz** [comment]
Please include a feature to fetch historical market data as well.

**Comment by ArabianCoconut** [comment]
> Please include a feature to fetch historical market data as well.

Sure will look into it as well.

**Comment by stunzz** [comment]
Please brother, implement the aforesaid feature. If you want I can pay you for that as well.

**Comment by ArabianCoconut** [comment]
> Please brother, implement the aforesaid feature. If you want I can pay you for that as well.

Please get in touch with me at **zwar73e7@duck.com** to discuss this further with payment options.

**Comment by ArabianCoconut** [comment]
Refer to #31 commit.
